package fr.polytech.conception.r1;

public enum Sports
{
    ACCROBRANCHE("Accrobranche"),
    ACROSPORT("Acrosport"),
    AEROBIC("Aérobic"),
    AEROMODELISME("Aéromodélisme"),
    AEROSTATION("Aérostation"),
    AGILITY("Agility"),
    AIKIDO("Aïkido"),
    AIRSOFT("Airsoft"),
    ALPINISME("Alpinisme"),
    AQUATHLON("Aquathlon"),
    ATHLETISME("Athlétisme"),
    AVIATION("Aviation"),
    AVIRON("Aviron"),
    APNEE("Apnée"),
    BABY_FOOT("Baby-foot"),
    BADMINTON("Badminton"),
    BASE_JUMP("Base-jump"),
    BASEBALL("Baseball"),
    BASKET_BALL("Basket-ball"),
    BATEAU_DRAGON("Bateau-Dragon"),
    BIATHLON("Biathlon"),
    BILLARD("Billard"),
    BLOC__ESCALADE_("Bloc (escalade)"),
    BMX("BMX"),
    BOARDERCROSS("Boardercross"),
    BOBSLEIGH("Bobsleigh"),
    BOCCIA("Boccia"),
    BODYBOARD("Bodyboard"),
    BOOMERANG("Boomerang"),
    BOWLING("Bowling"),
    BOXE("Boxe"),
    BRAS_DE_FER("Bras de fer"),
    CANICROSS("Canicross"),
    CANOE("Canoë"),
    CANOE_KAYAK("Canoë-kayak"),
    CANYONING("Canyoning"),
    CAPOEIRA("Capoeira"),
    CARROM("Carrom"),
    CATAMARAN("Catamaran"),
    CATCH("Catch"),
    CHEERLEADING("Cheerleading"),
    COASTEERING("Coasteering"),
    COMBAT("Combat"),
    COMPETITION_AUTOMOBILE("Compétition automobile"),
    COURSE_A_PIED("Course à pied"),
    COURSE_CAMARGUAISE("Course camarguaise"),
    COURSE_D_ORIENTATION("Course d'orientation"),
    CRICKET("Cricket"),
    CROQUET("Croquet"),
    CROSS__EQUITATION_("Cross (équitation)"),
    CROSS_COUNTRY("Cross-country"),
    CROSS_TRIATHLON("Cross triathlon"),
    CROSSE("Crosse"),
    CROSSFIT("CrossFit"),
    CULTURISME("Culturisme"),
    CURLING("Curling"),
    CYCLISME("Cyclisme"),
    CYCLO_CROSS("Cyclo-cross"),
    DANSE("Danse"),
    DAMES("Dames"),
    DECATHLON("Décathlon"),
    DELTAPLANE("Deltaplane"),
    DUATHLON("Duathlon"),
    DODGEBALL("Dodgeball"),
    DOUBLE_DUTCH("Double Dutch"),
    ECHECS("Échecs"),
    EQUITATION("Équitation"),
    ESCALADE("Escalade"),
    ESCRIME("Escrime"),
    ESPORTS("Esports"),
    FORMULE_1("Formule 1"),
    FLOORBALL("Floorball"),
    FOLKRACE("Folkrace"),
    FOOTBALL("Football"),
    FOOTBALL_AMERICAIN("Football américain"),
    FOOTBALL_AUSTRALIEN("Football australien"),
    FOOTBALL_GAELIQUE("Football gaélique"),
    FOOTING("Footing"),
    FUTSAL("Futsal"),
    GLISSE("Glisse"),
    GOLF("Golf"),
    GOUREN("Gouren"),
    GRAPPLING("Grappling"),
    GYMNASTIQUE("Gymnastique"),
    GYMNASTIQUE_RYTHMIQUE("Gymnastique rythmique"),
    HAKA_PEI("Haka pei"),
    HAKKO_RYU("Hakko-Ryu"),
    HALTEROPHILIE("Haltérophilie"),
    HANDBALL("Handball"),
    HOCKEY("Hockey"),
    HOCKEY_SUBAQUATIQUE("Hockey subaquatique"),
    HOCKEY_SUR_GAZON("Hockey sur gazon"),
    HOCKEY_SUR_GLACE("Hockey sur glace"),
    HORSE_BALL("Horse-ball"),
    HURLING("Hurling"),
    HAPKIDO_("Hapkido "),
    IAIDO("Iaïdo"),
    JEU_DE_PAUME("Jeu de paume"),
    JU_JITSU("Ju-Jitsu"),
    JOUTES_NAUTIQUES("Joutes nautiques"),
    JUDO("Judo"),
    JAVELOT_TIR_SUR_CIBLE("Javelot tir sur cible"),
    JIU_JITSU_BRESILIEN("Jiu-jitsu brésilien"),
    JET_SKI("Jet ski"),
    KABADDI("Kabaddi"),
    KANINHOP("Kaninhop"),
    KARATE("Karaté"),
    KARTING("Karting"),
    KAYAK("Kayak"),
    KEMPO("Kempo"),
    KENDO("Kendo"),
    KENJUTSU("Kenjutsu"),
    KICKBALL("Kickball"),
    KICK_BOXING("Kick-boxing"),
    KITESURFING("Kitesurfing"),
    KIN_BALL("Kin-ball"),
    KOBUDO("Kobudo"),
    KUNG_FU("Kung fu"),
    KRAV_MAGA("Krav maga"),
    KYUDO("Kyudo"),
    LANCER_DE_DISQUE("Lancer de disque"),
    LANCER_DE_JAVELOT("Lancer de javelot"),
    LANCER_DE_MARTEAU("Lancer de marteau"),
    LANCER_DE_POIDS("Lancer de poids"),
    LUGE_DE_COURSE("Luge de course"),
    LUTTE("Lutte"),
    MOTOMARINE("Motomarine"),
    MOTONEIGE("Motoneige"),
    VITESSE("vitesse"),
    ENDURANCE("endurance"),
    CROSS("cross"),
    TRIAL("trial"),
    ENDURO("enduro"),
    MUSCULATION("Musculation"),
    MARATHON("Marathon"),
    MMA("MMA"),
    NABAN("Naban"),
    NATATION("Natation"),
    NATATION_SYNCHRONISEE("Natation synchronisée"),
    NAUTISME("Nautisme"),
    NETBALL("Netball"),
    OMNIKIN("Omnikin"),
    OSLER_("osler "),
    PADDLE("Paddle"),
    PADEL("Padel"),
    PAINTBALL("Paintball"),
    PARACHUTISME("Parachutisme"),
    PARAPENTE("Parapente"),
    PARKOUR("Parkour"),
    PATIN_A_GLACE("Patin à glace"),
    PATINAGE("Patinage"),
    PATINAGE_ARTISTIQUE("Patinage artistique"),
    PATINAGE_DE_VITESSE("Patinage de vitesse"),
    PECHE_SPORTIVE("Pêche sportive"),
    PELOTE_BASQUE("Pelote basque"),
    PENTATHLON_MODERNE("Pentathlon moderne"),
    PETANQUE("Pétanque"),
    PILATES("Pilates"),
    PING_PONG("Ping-Pong"),
    PLANCHE_A_VOILE("Planche à voile"),
    PLANEUR("Planeur"),
    PLONGEE_EN_APNEE("Plongée en apnée"),
    PLONGEE("Plongée"),
    PLONGEE_SPORTIVE_EN_PISCINE("Plongée sportive en piscine"),
    PLONGEON("Plongeon"),
    PLUMFOOT("Plumfoot"),
    POLO("Polo"),
    QI_GONG("Qi gong"),
    QUAD("Quad"),
    QUIDDITCH("Quidditch"),
    QWAN_KI_DO("Qwan Ki Do"),
    RAFTING("Rafting"),
    RALLYE_AUTOMOBILE("Rallye automobile"),
    RAQUETTE_A_NEIGE("Raquette à neige"),
    REGATE("Régate"),
    RINGUETTE("Ringuette"),
    RINK_HOCKEY("Rink hockey"),
    ROLLER("Roller"),
    ROLLER_IN_LINE_HOCKEY("Roller in line hockey"),
    RUGBY_A_SEPT("Rugby à sept"),
    RUGBY_A_XIII("Rugby à XIII"),
    RUGBY_A_XV("Rugby à XV"),
    ROLLER_DERBY("Roller derby"),
    ROLLER_SOCCER__MINI_FOOT_EN_ROLLER_("Roller Soccer (mini foot en roller)"),
    SAMBO("Sambo"),
    SALSA("Salsa"),
    SAVATE("Savate"),
    SAUT_A_LA_PERCHE("Saut à la perche"),
    SAUT_A_SKI("Saut à ski"),
    SAUT_EN_HAUTEUR("Saut en hauteur"),
    SAUT_EN_LONGUEUR("Saut en longueur"),
    SHINTY("Shinty"),
    SKATEBOARD("Skateboard"),
    SKATER_HOCKEY("Skater hockey"),
    SKELETON("Skeleton"),
    SKI("Ski"),
    SKI_ALPIN("Ski alpin"),
    SKI_DE_FOND("Ski de fond"),
    SKI_NORDIQUE("Ski nordique"),
    SKI_NAUTIQUE("Ski nautique"),
    SLAMBALL("Slamball"),
    SNORKELING("Snorkeling"),
    SNOWBOARD("Snowboard"),
    SNOWSCOOT("Snowscoot"),
    SNOWSKATE("Snowskate"),
    SOFTBALL("Softball"),
    SPELEOLOGIE("Spéléologie"),
    SQUASH("Squash"),
    STEP("Step"),
    SUMO("Sumo"),
    SUPERMOTARD("Supermotard"),
    SURF("Surf"),
    TAE_BO("Tae Bo"),
    TAEKWONDO("Taekwondo"),
    TAI_CHI_CHUAN("Tai-chi-chuan"),
    TAIHOJUTSU("Taihojutsu"),
    TAISO("Taïso"),
    TAMBOURIN("Tambourin"),
    TANGO("Tango"),
    TAU_A_RAPA_NUI("Tau'a rapa nui"),
    TCHOUKBALL("Tchoukball"),
    TENNIS("Tennis"),
    TENNIS_DE_TABLE("Tennis de table"),
    TENNIS_LEGER("Tennis léger"),
    TIR_A_L_ARC("Tir à l'arc"),
    TIR_SPORTIF("Tir sportif"),
    TRIATHLON("Triathlon"),
    TRICKING("Tricking"),
    TRIPLE_SAUT("Triple saut"),
    TROTTINETTE_FREESTYLE("Trottinette freestyle"),
    TWIRLING("Twirling"),
    ULM("ULM"),
    ULTIMATE("Ultimate"),
    UNIHOCKEY("Unihockey"),
    VARAPPE("Varappe"),
    VELOCROSS__VELO_CROSS_COUNTRY__VTT_("Vélocross (vélo cross-country, VTT)"),
    VOILE("Voile"),
    VOLATA("Volata"),
    VOLLEY_BALL("Volley-ball"),
    VOLTIGE_AERIENNE("Voltige aérienne"),
    VOLTIGE_EN_CERCLE("Voltige en cercle"),
    WAKEBOARD("Wakeboard"),
    WATER_POLO("Water-polo"),
    WING_CHUN("Wing chun"),
    WAVEBOARD("Waveboard"),
    XARE("Xare"),
    YOGA("Yoga"),
    YOSEIKAN_BUDO("Yoseikan Budo"),
    ZEN_HAKKO_KAI("Zen Hakko Kaï"),
    ZUMBA("Zumba");

    private final String _sport;
    Sports(String sport)
    {
        this._sport = sport;
    }

    public String getSport()
    {
        return this._sport;
    }
}
